title: Flightdeck
subtitle: "Version 1.0.0, 11/13/21"
url: "https://flightdeck.ten7.com"
plugins:
    - jekyll-relative-links
    - jekyll-feed
    - jekyll-seo-tag
relative_links:
    enabled: true
    collections: true
include:
    - index.md
nav:
    - title: "Github"
      description: "Check out our Github"
      url: "https://github.com/ten7/flightdeck.ten7.com"
      is_mobile_nav_item: true
      is_button: true

footer:
  has_built_with_love: false
  html: |
    {{site.title}} ({{site.subtitle}}) published by <a href="https://ten7.com/">TEN7</a> and is licensed under the
    <a href="https://github.com/ten7/flightdeck.ten7.com/blob/main/LICENSE">GNU General Public License v3.0</a>. Feel free to
    <a href="https://github.com/ten7/flightdeck.ten7.com">use it for yourself</a>.

google_tag_manager:
  head_html: |
    <script>
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-N6K9NBR');
    </script>
  page_html: |
    <noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N6K9NBR"
    height="0" width="0" style="display: none; visibility: hidden"></iframe>
    </noscript>

markdown: kramdown

collections:
    pages:
        output: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - assets/_src/
    - clean-theme.gemspec
    - ansible/
    - ansible-hosts
    - ansible.cfg
    - Gemfile
    - Gemfile.lock
    - imagemin.js
    - LICENSE
    - node_modules/
    - npm-debug.log
    - package.json
    - package-lock.json
    - README.md
    - tsconfig.json
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - webpack.config.js
    - yarn.lock
